export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT ";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_CHANGE_IMAGE = "HANDLE_CHANGE_IMAGE";

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const SET_UPDATE_POST = "SET_UPDATE_POST";

export const UPDATE_POST_BEGIN = "UPDATE_POST_BEGIN";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";

export const GET_ALL_POST_BEGIN = "GET_ALL_POST_BEGIN";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";

export const GET_MY_POST_BEGIN = "GET_MY_POST_BEGIN";
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS";

export const CREATE_REVIEW_BEGIN = "CREATE_REVIEW_BEGIN";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SET_COMMENT_POST = "SET_COMMENT_POST";

export const GET_COMMENTS_BEGIN = "GET_COMMENTS_BEGIN";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";
